name: 'Prepare Cluster'
description: 'Prepare Cluster'
inputs:
  app-slug:
    description: 'App Slug.'
    required: true
    default: ''
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  chart:
    description: 'Path to the helm chart (One of `chart` or `yaml-dir` is required).'
    required: false
  yaml-dir:
    description: 'The directory containing multiple yamls for a Replicated release.'
    required: false
  kubernetes-distribution:
    description: 'Kubernetes distribution of the cluster to provision.'
    required: true
  kubernetes-version:
    description: 'Kubernetes version to provision (format is distribution dependent).'
    required: false
  cluster-name:
    description: 'Name of the cluster to provision'
    required: false
    default: ''
  ttl:
    description: 'Cluster TTL (duration, max 48h)'
    required: false
  disk:
    description: 'Disk size in GiB'
    required: false
  nodes:
    description: 'Number of nodes to provision'
    required: false
  min-nodes:
    description: 'Minimum number of nodes to provision'
    required: false
  max-nodes:
    description: 'Maximum number of nodes to provision'
    required: false
  instance-type:
    description: 'Instance type to provision'
    required: false
  timeout-minutes:
    description: 'Time to wait for the cluster to have a status of `running`'
    required: false
    default: '20'
  node-groups:
    description: |
      Node groups to provision.
      Example:
      <pre>node-groups: \|
        - name: "worker"
          instance-type: "t3.medium"
          disk: 100
          nodes: 3</pre>
    required: false
  tags:
    description: |
      Tags to assign to the cluster.
      Example:
      <pre>tags: \|
        - key: "department"
          value: "engineering"</pre>
    required: false
  kubeconfig-path:
    description: 'If specified, the kubeconfig will be written to this path'
    required: false
  export-kubeconfig:
    description: 'Export the KUBECONFIG variable (true/false)'
    required: false
    default: 'false'
  helm-values:
    description: 'A Helm values.yaml file to use'
    required: false
  helm-chart-name:
    description: 'The name of the Helm chart to use'
    required: false
  helm-run-preflights:
    description: 'Run preflight checks (true/false)'
    required: false
    default: 'true'
  kots-config-values:
    description: 'The KOTS config values to use'
    required: false
  kots-wait-duration:
    description: 'Timeout for KOTS to be used while waiting for individual components to be ready. must be in Go duration format (eg: 10s, 2m) (default "2m")'
    required: false
  customer-entitlements:
    description: |
      Entitlements to assign to the customer.
      Example:
      <pre>customer-entitlements: \|
        - name: "number-of-users"
          value: "10"</pre>
    required: false
outputs:
  cluster-id: # id of the cluster
    description: 'Contains the cluster id.'
    value: ${{ steps.create-cluster.outputs.cluster-id }}
  cluster-kubeconfig: # kubeconfig of the cluster
    description: 'Contains the kubeconfig to connect with the cluster.'
    value: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
runs:
  using: composite
  steps:
  - name: Create Release
    id: create-release
    shell: bash
    run: node ${{ github.action_path }}/create-release.js
    env:
      INPUT_APP-SLUG: ${{ inputs.app-slug }}
      INPUT_API-TOKEN: ${{ inputs.api-token }}
      INPUT_YAML-DIR: ${{ inputs.yaml-dir }}
      INPUT_CHART: ${{ inputs.chart }}
  - name: Create Customer
    id: create-customer
    shell: bash
    run: node ${{ github.action_path }}/create-customer.js
    env:
      INPUT_APP-SLUG: ${{ inputs.app-slug }}
      INPUT_API-TOKEN: ${{ inputs.api-token }}
      INPUT_CUSTOMER-NAME: ${{ github.ref_name }}-${{ inputs.kubernetes-distribution }}-${{ inputs.kubernetes-version }}
      INPUT_CUSTOMER-EMAIL: ${{ github.ref_name }}@example.com
      INPUT_LICENSE-TYPE: "test"
      INPUT_ENTITLEMENTS: ${{ inputs.customer-entitlements }}
      INPUT_CHANNEL-SLUG: ${{ steps.create-release.outputs.channel-slug }}
      INPUT_IS-KOTS-INSTALL-ENABLED: "false"
  - name: Create Cluster
    id: create-cluster
    shell: bash
    run: node ${{ github.action_path }}/create-cluster.js
    env:
      INPUT_API-TOKEN: "${{ inputs.api-token }}"
      INPUT_KUBERNETES-DISTRIBUTION: ${{ inputs.kubernetes-distribution }}
      INPUT_KUBERNETES-VERSION: ${{ inputs.kubernetes-version }}
      INPUT_CLUSTER-NAME: ${{ inputs.cluster-name || format('{0}-{1}-{2}', github.ref_name, inputs.kubernetes-distribution, inputs.kubernetes-version) }}
      INPUT_TTL: ${{ inputs.ttl || '' }}
      INPUT_DISK: ${{ inputs.disk || '' }}
      INPUT_NODES: ${{ inputs.nodes || '' }}
      INPUT_MIN-NODES: ${{ inputs.min-nodes || '' }}
      INPUT_MAX-NODES: ${{ inputs.max-nodes || '' }}
      INPUT_INSTANCE-TYPE: ${{ inputs.instance-type || '' }}
      INPUT_TIMEOUT-MINUTES: ${{ inputs.timeout-minutes || 20 }}
      INPUT_NODE-GROUPS: ${{ inputs.node-groups || '' }}
      INPUT_TAGS: ${{ inputs.tags || '' }}
      INPUT_KUBECONFIG-PATH: ${{ inputs.kubeconfig-path || '' }}
      INPUT_EXPORT-KUBECONFIG: ${{ inputs.export-kubeconfig || false }}
  # - name: Deploy the app with Helm
  #   uses: replicatedhq/compatibility-actions/helm-install@${{ env.action_ref }}
  #   if: ${{ inputs.chart != '' }}
  #   with:
  #     kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
  #     helm-path: "helm"
  #     registry-username: ${{ github.ref_name }}@example.com
  #     registry-password: ${{ steps.create-customer.outputs.license-id }}
  #     chart: oci://registry.replicated.com/${{ inputs.app-slug }}/release__${{ steps.create-release.outputs.release-sequence }}/${{ inputs.helm-chart-name }}
  #     name: ${{ inputs.app-slug }}
  #     namespace: 'default'
  #     values: ${{ inputs.helm-values }}
  #     run-preflights: ${{ inputs.helm-run-preflights }}
  # - name: Deploy the app with KOTS
  #   if: ${{ inputs.yaml-dir != '' }}
  #   uses: replicatedhq/compatibility-actions/kots-install@${{ env.action_ref }} 
  #   with:
  #     kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
  #     INPUT_APP-SLUG: ${{ inputs.app-slug }}/test-channel
  #     license-file: ${{ steps.create-customer.outputs.license-file }}
  #     app-version-label: release__${{ steps.create-release.outputs.release-sequence }}
  #     config-values: ${{ inputs.kots-config-values }}
  #     wait-duration: ${{ inputs.kots-wait-duration }}
