name: "Remove cluster"
description: "Remove a cluster"
inputs:
  api-token:
    description: "API Token."
    required: true
    default: ""
  cluster-id:
    description: "Cluster id to remove."
    required: true
runs:
  using: "composite"
  steps:
    - run: node dist/index.js remove-cluster
      shell: bash
