name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: |
            **/package-lock.json

      - name: package
        run: make package-all

      - name: readme
        run: make readme-all

      - name: fail if files changed
        run: |
          if ! git diff --quiet --exit-code ; then
            echo "Please run 'make package-all' and 'make readme-all' locally and commit the changes."
            exit 1
          fi
